http://localhost:8080/api/books

###

http://localhost:8080/api/books/633548e692df1eddeed375d6

###

DELETE http://localhost:8080/api/books/633548e692df1eddeed375d6

###
POST http://localhost:8080/api/books
Content-Type: application/json

{
    "title": "テストデータ",
    "description": "説明欄の内容",
    "comment": "コメントの内容",
    "rating": 5
}

###

PATCH http://localhost:8080/api/books/66bdfe5612e8cd1d17a303d9
Content-Type: application/json

{
    "title": "テストデータ1",
    "description": "説明欄の内容2",
    "comment": "コメントの内容3",
    "rating": 4
}